on: pull_request
jobs:
  lintAndTest:
    name: Run linters and then tests
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - name: Use Node.js
        uses: actions/setup-node@v2
        with:
          node-version-file: ".nvmrc"
          cache: "npm"
      - name: Install dependencies
        run: npm ci
      - name: Run ESLint
        run: npm run lint:scripts
      - name: Run Stylelint
        run: npm run lint:styles
      - name: Run Tests
        run: npm test
        env:
          CI: true
